name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node/pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Run script
      run: |
        pnpm build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        publish_branch: gh-pages
